---
title: "Data Visualization"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readr)

fantasy <- read_csv("data/fantasy.csv")
```

```{r bpm_fpts}
ggplot(fantasy, aes(bpm, fpts_100)) +
  geom_point() +
  annotate(geom = "text", x = -20, y = -25, label = paste("r = ",format(round(cor(fantasy$bpm, fantasy$fpts_100),4))), colour = "blue") +
  labs(
    title = "Fantasy Points vs BPM",
    x = "BPM",
    y = "Fantasy Points"
  ) +
  theme_classic() +
  geom_smooth(method = "lm") 
```

```{r per_fpts}
ggplot(fantasy, aes(per, fpts_100)) +
  geom_point()+
  annotate(geom = "text", x = -5, y = -10, label = paste("r = ",format(round(cor(fantasy$per, fantasy$fpts_100),4))), colour = "blue") +
  labs(
    title = "Fantasy Points vs PER",
    x = "PER",
    y = "Fantasy Points"
  ) +
  theme_classic() +
  geom_smooth(method = "lm") 
  

```

```{r obpm_fpts}
ggplot(fantasy, aes(obpm, fpts_100)) +
  geom_point()+
  annotate(geom = "text", x = -5, y = -10, label = paste("r = ",format(round(cor(fantasy$obpm, fantasy$fpts_100),4))), colour = "blue") +
  labs(
    title = "Fantasy Points vs OBPM",
    x = "OBPM",
    y = "Fantasy Points"
  ) +
  theme_classic() +
  geom_smooth(method = "lm") 
  
```

```{r pts_fpts}
ggplot(fantasy, aes(pts, fpts_100)) +
  geom_point()+
  annotate(geom = "text", x = 45, y = 30, label = paste("r = ",format(round(cor(fantasy$pts, fantasy$fpts_100),4))), colour = "blue") +
  labs(
    title = "Fantasy Points vs Points",
    x = "Points",
    y = "Fantasy Points"
  ) +
  theme_classic() +
  geom_smooth(method = "lm") 
  
```

